name: Build and Deploy MkDocs

on:
  push:
    branches:
      - main  # Quando houver alteraÃ§Ãµes na branch 'main'
    paths:
      - 'docs/**'  # Quando houver mudanÃ§as na pasta 'docs'

permissions:
  contents: write  # PermissÃµes necessÃ¡rias para publicar no GitHub Pages

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}  # Evita mÃºltiplos deploys simultÃ¢neos

    runs-on: ubuntu-latest  # A mÃ¡quina de build que serÃ¡ utilizada no GitHub Actions
    
    steps:
      - name: Checkout repository ğŸ›ï¸
        uses: actions/checkout@v4  # Faz o checkout do cÃ³digo do repositÃ³rio

      - name: Set up Python environment ğŸ
        uses: actions/setup-python@v4  # Configura o Python para o ambiente
        with:
          python-version: '3.9'  # Defina a versÃ£o do Python desejada

      - name: Install MkDocs and mkdocs-material ğŸ§°
        run: |
          python -m pip install --upgrade pip  # Atualiza o pip
          pip install mkdocs  # Instala o MkDocs
          pip install mkdocs-material  # Instala o tema mkdocs-material

      - name: Build the MkDocs site ğŸ—ï¸
        run: mkdocs build --clean  # Gera os arquivos estÃ¡ticos na pasta 'site'

      - name: Deploy to GitHub Pages ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4  # AÃ§Ã£o para deploy no GitHub Pages
        with:
          branch: gh-pages  # A branch onde o site serÃ¡ publicado
          folder: site      # A pasta onde os arquivos gerados pelo MkDocs sÃ£o armazenados
          target-folder: ./ # Envia os arquivos para a raiz da branch 'gh-pages'
          token: ${{ secrets.GITHUB_TOKEN }}  # Token de autenticaÃ§Ã£o do GitHub Actions
